config/routes.rb
Rails.application.routes.draw do
  get 'games/new'
  get 'notes/index'
  #get 'items/new'
  get 'items/index'
  get 'villagers/index'
  resources :games do
    resources :items
    resources :villagers
    resources :notes
  end
  resources :preferences
  get 'application/index'

  root 'games#index'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :game

  NOTE_TYPES = [
    "Farming",
    "Mining",
    "Relationships",
    "General"
  ]

validates :additional_info, presence: { message: "cannot be blank" }

  def self.sort_by_type
    Note.all.group_by(&:info_type)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :get_game

  def index
    @notes = @game.notes.sort_by_type
  end

  def new
    @note = @game.notes.new
  end

  def create
    @note = @game.notes.new(note_params)

    if @note.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def edit
    @note = @game.notes.find(params[:id])
  end

  def update
    @note = @game.notes.find(params[:id])

    @note.update_attributes(note_params)

    if @note.save
      redirect_to game_path(@game)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @note = @game.notes.find(params[:id])
    @note.destroy
    redirect_to game_path(@game)
  end

  private
    def note_params
      params.require(:note).permit(:additional_info, :info_type)
    end

    def get_game
      @game = Game.find(params[:game_id])
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with model: model, local: true do |form| %>
<%= render 'error_messages', model: model.last %>
  <div class="form-input-element">
    <%= form.label :info_type %><br>
    <%= form.select :info_type, Note::NOTE_TYPES %>
  </div>
  <div class="form-input-element">
    <%= form.label :additional_info %><br>
    <%= form.text_area :additional_info, size: "30x10", class: "extra-info-text-area" %>
  </div>

  <div class="form-input-element">
    <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/notes/_index.html.erb
<div class="full-page-notes-embedded">
  <div class="inner-page">
    <div class="page-header-title-button">
      <h1 class="page-title">Notes</h1>
      <%= link_to 'Add New Note', new_game_note_path(@game), class: "button add-new-link" %>
    </div>
    <table>
      <thead>
        <% @notes.each do |type, note| %>
          <% unless @notes[type].empty? %>
            <tr>
              <th class="header", scope="col"><%= type %></th>
              <th></th>
            </tr>
          <% end %>
        </thead>
        <tbody>
          <% note.each do |info| %>
            <tr>
              <td class="additional-info"><%= sanitize(info.additional_info) %></td>
              <td><%= link_to 'Edit', edit_game_note_path(@game, info), class: "button" %></td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/notes/edit.html.erb
<% provide(:title, "Edit Note") %>
<div class="full-page">
  <div class="inner-page">
    <h1 class="page-title">Edit Note</h1>

    <%= render "form", model: [@game, @note] %>

    <%= button_to 'Delete Note', game_note_path, class: "button delete-button",
                                     method: :delete,
                                     data: { confirm: "Really delete this note?" } %>
  </div>
</div>

app/views/notes/index.html.erb
<div class="full-page">
  <div class="inner-page">
    <div class="page-header-title-button">
      <h1 class="page-title">Notes</h1>
      <%= link_to 'Add New Note', new_note_path, class: "button add-new-link" %>
    </div>
  <table>
    <thead>
      <% @notes.each do |type, note| %>
        <% unless @notes[type].empty? %>
          <tr>
            <th class="header", scope="col"><%= type %></th>
            <th></th>
          </tr>
        <% end %>
      </thead>
      <tbody>
        <% note.each do |info| %>
          <tr>
            <td class="additional-info"><%= sanitize(info.additional_info) %></td>
            <td><%= link_to 'Edit', edit_note_path(info), class: "button" %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
  </table>
  </div>
</div>

app/views/notes/new.html.erb
<% provide(:title, "Add Note") %>
<div class="full-page">
  <div class="inner-page">
    <h1 class="page-title">New Note</h1>

    <%= render "form", model: [@game, @note] %>
  </div>
</div>

app/views/notes/show.html.erb
<h1>Notes#show</h1>
<p>Find me in app/views/notes/show.html.erb</p>