config/routes.rb
Rails.application.routes.draw do
  get 'games/new'
  get 'notes/index'
  #get 'items/new'
  get 'items/index'
  get 'villagers/index'
  resources :games do
    resources :items
    resources :villagers
    resources :notes
  end
  resources :preferences
  get 'application/index'

  root 'games#index'
end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :villager
  belongs_to :item

  OPINIONS = [
    "Likes",
    "Dislikes"
  ]

  validates_uniqueness_of :villager_id, scope: :item_id, message: "preference is already set"
  validates :opinion, inclusion: { in: OPINIONS }
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  def new
    @preference = Preference.new
  end

  def index
    @preferences = Preference.all
    ## This redirect is a current workaround to avoid accessing Preferences/index
    redirect_to controller: 'games', action: 'index'
  end

  def create
    @preference = Preference.new(preference_params)
    @game = get_game

    if @preference.save
      redirect_back(fallback_location: game_villagers_path(@game))
    else
      render :new
    end
  end

  def show
    @preference = Preference.find(params[:id])
  end

  def destroy
    @preference = Preference.find(params[:id])
    @game = get_game
    @preference.destroy
    redirect_back(fallback_location: game_villagers_path(@game))
  end

  private
    def preference_params
      params.require(:preference).permit(:villager_id, :item_id, :opinion)
    end

    def get_game
      if @preference.villager_id.present?
        @villager = Villager.find(@preference.villager_id)
        Game.find { |game| game.id == @villager.game_id }
      else
        @item = Item.find(@preference.item_id)
        Game.find { |game| game.id == @item.game_id }
      end
    end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
  def villager_name(villager_id)
    Villager.find(villager_id).name
  end

  def item_name(item_id)
    Item.find(item_id).name
  end
end

app/views/preferences/_form.html.erb
<%= form_with model: model ||= Preference.new, villager_select: villager_select ||= nil, item_select: item_select ||= nil, local: true do |form| %>
  <%= render 'error_messages', model: model %>
  <div class="form-input-element">
    <% if villager_select != nil %>
      <%= form.hidden_field :villager_id, value: villager_select %>
    <% else %>
      <%= form.label :villager, "Villager:" %><br>
      <%= form.collection_select :villager_id, @game.villagers.order(:name), :id, :name, prompt: true %>
    <% end %>
  </div>
  <div class="form-input-element">
    <% if item_select != nil %>
      <%= form.hidden_field :item_id, value: item_select %>
    <% else %>
      <%= form.label :item, "Item:" %><br>
      <%= form.collection_select :item_id, @game.items.order(:name), :id, :name, prompt: true %>
    <% end %>
  </div>
  <div class="form-input-element create-preference-choices">
      <%= form.radio_button :opinion, "Likes" %><%= form.label :opinion, "Likes", value: "Likes" %>
      <%= form.radio_button :opinion, "Dislikes" %><%= form.label :opinion, "Dislikes", value: "Dislikes" %>
  </div>
  <div class="form-input-element create-preference-button">
      <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/preferences/index.html.erb
<% provide(:title, "Preferences") %>
<div class="full-page">
  <div class="inner-page">
    <div class="page-header-title-button">
      <h1 class="page-title">Preferences:</h1>
      <%= link_to 'Add New Preference', new_preference_path, class: "button add-new-link" %>
    </div>
    <br>
    <br>
    <table>
      <thead>
        <tr>
          <th class="header", scope="col">Villager</th>
          <th class="header", scope="col">Item</th>
          <th class="header", scope="col">Preference</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @preferences.order(:villager_id).each do |pref| %>
          <tr>
            <td><%= villager_name(pref.villager_id) %></td>
            <td><%= item_name(pref.item_id) %></td>
            <td><%= pref.opinion %></td>
            <td><%= button_to 'Delete', preference_path(pref), class: "button delete-button",
                                             method: :delete,
                                             data: { confirm: "Really delete?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/preferences/new.html.erb
<% provide(:title, "Add Preference") %>
<div class="full-page">
  <div class="inner-page preference-page-inner">
    <h1 class="page-title">Create Villager Preference</h1>

    <%= render 'form', model: @preference %>
  </div>
</div>