config/routes.rb
Rails.application.routes.draw do
  get 'games/new'
  get 'notes/index'
  #get 'items/new'
  get 'items/index'
  get 'villagers/index'
  resources :games do
    resources :items
    resources :villagers
    resources :notes
  end
  resources :preferences
  get 'application/index'

  root 'games#index'
end

app/models/item.rb
class Item < ApplicationRecord
  extend Sorter
  has_many :preferences, dependent: :destroy
  has_many :villagers, through: :preferences
  belongs_to :game

  CATEGORIES = [
    "Animal Products",
    "Artifacts",
    "Artisan Goods",
    "Cooked Dishes",
    "Fish",
    "Flowers",
    "Fruit",
    "Minerals",
    "Trash",
    "Vegetables"
  ]

  validates :name, { presence: true, uniqueness:
                                    { scope: :game,
                                      case_sensitive: false,
                                      message: "already exists" }
}
  validates :category, inclusion: { in: CATEGORIES }
  validates :sale_price, numericality: { only_integer: true }, allow_blank: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :get_game

  def new
    @item = @game.items.new
  end

  def index
    @items_all = @game.items
    if params[:search]
      @items = @items_all.search(params[:search])
    elsif !params[:filter].blank?
      @items = @items_all.filter(:category, params[:filter])
    else
      @items = @items_all
    end
  end

  def create
    @item = @game.items.new(item_params)

    if @item.save
      redirect_to game_item_path(@game, @item)
    else
      render :new
    end
  end

  def show
    @item = @game.items.find(params[:id])

    @preferences = get_prefs
    @likes = get_opinions("Likes")
    @dislikes = get_opinions("Dislikes")
  end

  def edit
    @item = @game.items.find(params[:id])
    @preferences = get_prefs
  end

  def update
    @item = @game.items.find(params[:id])

    @item.update_attributes(item_params)

    if @item.save
      redirect_to game_item_path
    else
      @preferences = get_prefs
      render :edit
    end
  end

  def destroy
    @item = @game.items.find(params[:id])
    @item.destroy
    redirect_to game_items_path
  end

  private
    def item_params
      params.require(:item).permit(:name, :category, :sale_price, :extra_info, :search, :filter)
    end

    def get_prefs
      Preference.where(item_id: @item.id)
    end

    def get_opinions(pref)
      @preferences.select { |prefs| prefs.opinion == pref }
      .map { |like| Villager.find(like.villager_id) }
    end

    def get_game
      @game = Game.find(params[:game_id])
    end

    # def get_game_name
    #   if @item.game_id.nil?
    #     "None"
    #   else
    #     Game.find(@item.game_id).name
    #   end
    # end

    #def find_villager_names(villagers)
      #Villager.find(villagers.villager_id).name
    #end
end

app/helpers/items_helper.rb
module ItemsHelper
  def item_pic(game_name, item_name)
    if File.exists?(Rails.root.join("app/assets/images/#{titleize_image_link(game_name)}/items/#{titleize_image_link(item_name)}.png"))
      image_tag "#{titleize_image_link(game_name)}/items/#{titleize_image_link(item_name)}.png", alt: "#{item_name} picture", class: "item-pic"
    elsif File.exists?(Rails.root.join("app/assets/images/#{titleize_image_link(game_name)}/items/placeholder.png"))
      image_tag "#{titleize_image_link(game_name)}/items/placeholder.png", alt: "#{item_name} picture", class: "item-pic"
    else
      image_tag "items/placeholder.png", class: "item-pic"
    end
  end
end

app/views/items/_form.html.erb
<%= form_with model: model, local: true do |form| %>
<%= render 'error_messages', model: model.last %>
  <div class="form-input-element">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div class="form-input-element">
    <%= form.label :category %><br>
    <%= form.select :category, Item::CATEGORIES %><br>
  </div>
  <div class="form-input-element">
      <%= form.label :sale_price %><br>
      <%= form.text_field :sale_price %>
  </div>
  <div class="form-input-element">
    <%= form.label :extra_info %><br>
    <%= form.text_area :extra_info, size: "30x10", class: "extra-info-text-area" %>
  </div>
  <div class="form-input-element">
    <%= form.submit class: "button" %>
  </div>
  <% end %>

app/views/items/edit.html.erb
<% provide(:title, "Edit Item") %>
<div class="full-page">
  <div class="inner-page">
    <h1 class="page-title">Edit Item Info</h1>

    <%= render "form", model: [@game, @item] %>
    <div class="profile-page-preference-table">
      <table>
        <tr>
          <th>Villager</th>
          <th>Preference</th>
        </tr>

      <% @preferences.order(:villager_id).each do |pref| %>
        <tr>
          <td><%= villager_name(pref.villager_id) %></td>
          <td><%= pref.opinion %></td>
          <td><%= button_to 'Delete', preference_path(pref), class: "button delete-button",
                                           method: :delete,
                                           data: { confirm: "Really delete this preference?" } %></td>
        </tr>
      <% end %>
      </table>
    </div>

    <%= button_to 'Delete Item', game_item_path, class: "button",
                                 method: :delete,
                                 data: { confirm: "Really delete #{@item.name}?" } %>
    <br>
    <br>
    <%= link_to "#{@item.name} Page", game_item_path, class: "button" %>
  </div>
</div>

app/views/items/index.html.erb
<% provide(:title, "#{@game.name} Items") %>
<div class="full-page">
  <div class="inner-page">
    <div class="page-header-title-button">
      <h1 class="page-title"><%= "#{@game.name}" %> Items List</h1>
      <%= link_to 'Add New Item', new_game_item_path, class: "button add-new-link" %>
    </div>
    <div class="search-filter">
      <div class="search-header">Search By Name:<%= form_with url: game_items_path, method: :get, local: true do |form| %>
        <%= form.text_field :search, value: params[:search], class: "search-style" %>
        <%= form.submit 'Search', name:nil, class: "button search-button" %>
      <% end %>
      </div>
      <div class="filter-header">Filter By Category:<%= form_with url: game_items_path, method: :get, local: true do |form| %>
        <%= form.select :filter, Item::CATEGORIES, selected: params[:filter], include_blank: "All Items" %>
        <%= form.submit 'Filter', name:nil, class: "button filter-button" %>
      <% end %>
      </div>
    </div>
    <table>
      <thead>
        <tr>
          <th class="header", colspan="2", scope="col">Item</th>
          <th class="header", scope="col">Category</th>
          <th class="header", scope="col">Sale Price</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @items.order(:name).each do |item| %>
          <tr>
            <td><%= item_pic(@game.name, item.name) %></td>
            <td><%= item.name %></td>
            <td><%= item.category %></td>
            <td><%= item.sale_price %></td>
            <td><%= link_to 'Item Page', game_item_path(@game, item), class: "button" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/items/new.html.erb
<% provide(:title, "Add Item") %>
<div class="full-page">
  <div class="inner-page">
    <h1 class="page-title">New Item</h1>

    <%= render "form", model: [@game, @item] %>
  </div>
</div>

app/views/items/show.html.erb
<% provide(:title, "#{@item.name}") %>
<div class="full-page">
  <div class="inner-page">
    <div class="individual-page-title">
      <h1><%= @item.name %></h1>
      <span class="individual-page-pic"><%= item_pic(@game.name, @item.name) %></span>
    </div>
    <table>
      <tr>
        <th class="header", scope="col">Game</th>
        <td><%= @game.name %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Category</th>
        <td><%= @item.category %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Sale Price</th>
        <td><%= @item.sale_price %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Preferences</th>
        <td><%= render 'display_preferences' %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Add Preference</th>
        <td><%= render "preferences/form", model: Preference.new, item_select: @item.id %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Additional Info</th>
        <td class="additional-info"><%= sanitize(@item.extra_info) %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Updates?</th>
        <td><%= link_to 'Edit Item', edit_game_item_path, class: "button" %></td>
      </tr>
    </table>
  </div>
</div>