config/routes.rb
Rails.application.routes.draw do
  get 'games/new'
  get 'notes/index'
  #get 'items/new'
  get 'items/index'
  get 'villagers/index'
  resources :games do
    resources :items
    resources :villagers
    resources :notes
  end
  resources :preferences
  get 'application/index'

  root 'games#index'
end

app/models/villager.rb
class Villager < ApplicationRecord
  extend Sorter
  has_many :preferences, dependent: :destroy
  has_many :items, through: :preferences
  belongs_to :game

  BIRTH_SEASONS = %w(Spring Summer Fall Winter)
  BIRTH_DAYS = (1..30).to_a

  validates :name, { presence: true, uniqueness:
                                    { scope: :game,
                                      case_sensitive: false,
                                      message: "already exists" } }
  validates :birth_season, inclusion: { in: BIRTH_SEASONS,
    message: "%{value} is not a valid season" }
  validates :birth_day, inclusion: { in: BIRTH_DAYS,
    message: "%{value} is not a valid date" }
end

app/controllers/villagers_controller.rb
class VillagersController < ApplicationController
  before_action :get_game

  def new
    @villager = @game.villagers.new
  end

  def index
    @villagers_all = @game.villagers

    if params[:search]
      @villagers = @villagers_all.search(params[:search])
    elsif !params[:filter].blank?
      @villagers = @villagers_all.filter(:birth_season, params[:filter])
    else
      @villagers = @villagers_all
    end
  end

  def create
    @villager = @game.villagers.new(villager_params)

    if @villager.save
      redirect_to game_villager_path(@game, @villager)
    else
      render :new
    end
  end

  def show
    @villager = @game.villagers.find(params[:id])

    @preferences = get_prefs
    @likes = get_opinions("Likes")
    @dislikes = get_opinions("Dislikes")
  end

  def edit
    @villager = @game.villagers.find(params[:id])
    @preferences = get_prefs
  end

  def update
    @villager = @game.villagers.find(params[:id])

    @villager.update_attributes(villager_params)

    if @villager.save
      redirect_to game_villager_path
    else
      @preferences = get_prefs
      render :edit
    end
  end

  def destroy
    @villager = @game.villagers.find(params[:id])
    @villager.destroy
    redirect_to game_villagers_path
  end

  private
    def villager_params
      params.require(:villager).permit(:name, :birth_day, :birth_season, :extra_info, :search, :filter)
    end

    def get_prefs
      Preference.where(villager_id: @villager.id)
    end

    def get_opinions(pref)
      @preferences.select { |prefs| prefs.opinion == pref }
      .map { |like| Item.find(like.item_id) }
    end

    def get_game
      @game = Game.find(params[:game_id])
    end
end

app/helpers/villagers_helper.rb
module VillagersHelper
  def headshot(game_name, villager_name)
    if File.exists?(Rails.root.join("app/assets/images/#{titleize_image_link(game_name)}/villagers/#{titleize_image_link(villager_name)}.png"))
      image_tag "#{titleize_image_link(game_name)}/villagers/#{titleize_image_link(villager_name)}.png", alt: "#{villager_name} headshot", class: "headshot"
    elsif File.exists?(Rails.root.join("app/assets/images/#{titleize_image_link(game_name)}/villagers/placeholder.png"))
      image_tag "#{titleize_image_link(game_name)}/villagers/placeholder.png", alt: "#{villager_name} headshot", class: "headshot"
    else
      image_tag "villagers/placeholder.png", class: 'headshot'
    end
  end
end

app/views/villagers/_form.html.erb
<%= form_with model: model, local: true do |form| %>
<%= render 'error_messages', model: model.last %>
  <div class="form-input-element">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div class="form-input-element">
    <%= form.label :birth_season, "Birth Season" %><br>
    <%= form.select :birth_season, Villager::BIRTH_SEASONS %>
  </div>
  <div class="form-input-element">
    <%= form.label :birth_day, "Birth Day" %><br>
    <%= form.select :birth_day, Villager::BIRTH_DAYS %>
  </div>
  <div class="form-input-element">
    <%= form.label :extra_info %><br>
    <%= form.text_area :extra_info, size: "30x10", class: "extra-info-text-area" %>
  </div>
  <div class="form-input-element">
    <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/villagers/edit.html.erb
<% provide(:title, "Edit Villager") %>
<div class="full-page">
  <div class="inner-page">
    <h1 class="page-title">Edit Villager Info</h1>

    <%= render "form", model: [@game, @villager] %>
    <div class="profile-page-preference-table">
      <table>
        <tr>
          <th>Item</th>
          <th>Preference</th>
        </tr>
      <% @preferences.each do |pref| %>
        <tr>
          <td><%= item_name(pref.item_id) %></td>
          <td><%= pref.opinion %></td>
          <td><%= button_to 'Delete', preference_path(pref), class: "button delete-button",
                                           method: :delete,
                                           data: { confirm: "Really delete this preference?" } %></td>
        </tr>
      <% end %>
      </table>
    </div>
    <%= button_to 'Delete Villager', game_villager_path, class: "button",
                                     method: :delete,
                                     data: { confirm: "Really delete #{@villager.name}?" } %>
    <br>
    <br>
    <%= link_to "#{@villager.name}'s Page", game_villager_path, class: "button" %>
  </div>
</div>

app/views/villagers/index.html.erb
<% provide(:title, "#{@game.name} Villagers") %>
<div class="full-page">
  <div class="inner-page">
    <div class="page-header-title-button">
      <h1 class="page-title"><%=" #{@game.name}" %> Villagers List</h1>
      <%= link_to 'Add New Villager', new_game_villager_path, class: "button add-new-link" %>
    </div>
    <div class="search-filter">
      <div class="search-header">Search By Name:<%= form_with url: game_villagers_path, method: :get, local: true do |form| %>
        <%= form.text_field :search, value: params[:search], class: "search-style" %>
        <%= form.submit 'Search', name:nil, class: "button search-button" %>
      <% end %>
      </div>
      <div class="filter-header">Filter By Birth Season:<%= form_with url: game_villagers_path, method: :get, local: true do |form| %>
        <%= form.select :filter, Villager::BIRTH_SEASONS, selected: params[:filter], include_blank: "All Villagers" %>
        <%= form.submit 'Filter', name:nil, class: "button filter-button" %>
      <% end %>
      </div>
    </div>
    <table>
      <thead>
        <tr>
          <th class="header", colspan="2", scope="col">Villager</th>
          <th class="header", scope="col">Birthday</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @villagers.order(:name).each do |villager| %>
          <tr>
            <td><%= headshot(@game.name, villager.name) %></td>
            <td><%= villager.name %></td>
            <td><%= "#{villager.birth_season} #{villager.birth_day}" %></td>
            <td><%= link_to 'Profile', game_villager_path(@game, villager), class: "button" %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/villagers/new.html.erb
<% provide(:title, "Add Villager") %>
<div class="full-page">
  <div class="inner-page">
    <h1 class="page-title">New Villager</h1>

    <%= render "form", model: [@game, @villager] %>
  </div>
</div>

app/views/villagers/show.html.erb
<% provide(:title, "#{@villager.name}") %>
<div class="full-page">
  <div class="inner-page">
    <div class="individual-page-title">
      <h1><%= @villager.name %></h1>
      <span class="individual-page-pic"><%= headshot(@game.name, @villager.name) %></span>
    </div>
    <table>
      <tr>
        <th class="header", scope="col">Game</th>
        <td><%= @game.name %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Birth Date</th>
        <td><%= @villager.birth_season %> <%= @villager.birth_day %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Preferences</th>
        <td><%= render 'display_preferences' %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Add Preference</th>
        <td><%= render "preferences/form", model: Preference.new, villager_select: @villager.id %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Additional Info</th>
        <td class="additional-info"><%= sanitize(@villager.extra_info) %></td>
      </tr>
      <tr>
        <th class="header", scope="col">Updates?</th>
        <td><%= link_to 'Edit Villager', edit_game_villager_path, class: "button" %></td>
      </tr>
    </table>
  </div>
</div>